package joneill.euler;
/***
 * @author josep_000
 * 
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms
 *
 ***/

public class Euler2 {
	private static long sum;
	private static long previousNum;
	private static long currNum;
	
	public static void main(String args[]) {
		getAnswer();
		System.out.println(Long.toString(sum));
	}
	
	private static void getAnswer() {
		currNum = 1;
		do {
			long previousNumber = 0;
			previousNumber = currNum;
			currNum += previousNum;
			previousNum = previousNumber;
			if(currNum % 2 == 0 && currNum < 4000000) {
				sum += currNum;
			}
		} while (currNum < 4000000);
	}
}
